### ISSUE TITLE
💬 Feedback - Improve Documentation with step by step guide to create component

### ISSUE THREAD

**Issue by zecka** [contentful/template-marketing-webapp-nextjs#204]
First of all, congratulations for this great work on this template! The dev experience is very pleasant!

My first attempt was to create a basic component that I could use on the home page.

Despite [the steps described in the README](https://github.com/contentful/template-marketing-webapp-nextjs/blob/main/README.md#creating-new-contentful-components) I took some time to understand what steps to follow to create a component.

It would be good to add a step by step guide to create a component from Contentful to React code.

Maybe this guide already exists and I just couldn't find it?

I wrote down the steps I followed to create my first component

# Goal
Create a component with a "Title" field that can be inserted on the home page

# On Contentful backoffice

1. Go to Content model → +Add content type
2. On name field  → **💎 Demo component**
3. On Api Identifier → componentDemo  
   **( !!! This will be used in the code and it may be difficult to change it later, make sure you use a correct identifier)**
5. Click “Create”
6. Click “Add a field” → Text (Name: title, field ID: title)
7. Check “This field represents the Entry title” —> Confirm —> Save
8. On “Content model” → **📜 Landing page →** Top section → click on “Settings”
9. Add “💎 Demo component” to list bellow **Accept only specified entry type →** confirm → Save
10. On “Content” → Add entry → **💎 Demo component**
11. On title → Demo Component Example
12. Click on Publish
13. On Content → Homepage → Top Section → Add existing content → Demo Component Example → Insert 1 Entry → “Publish changes”

# On Code repository

Run following command 

```bash
yarn run graphql-codegen:generate
```

## Create component graphql query

src/components/features/ctf-components/ctf-demo/ctf-demo.tsx

*Note that `componentDemo` in the query represent your **Api Identifier** previously defined*

```graphql
fragment DemoFields on ComponentDemo {
  __typename
  sys {
    id
  }
  title
}

query CtfDemo($id: String!, $locale: String, $preview: Boolean) {
  componentDemo(id: $id, locale: $locale, preview: $preview) {
    ...DemoFields
  }
}
```

## Create Functional components

[More detail here](https://github.com/contentful/template-marketing-webapp-nextjs/blob/main/README.md#contentful-components)

`src/components/features/ctf-components/ctf-demo/ctf-demo.tsx`

the React component which is actually rendering the content type.

```tsx
import { makeStyles } from '@mui/styles';
import { Theme } from '@mui/material';
import { DemoFieldsFragment } from './__generated/ctf-demo.generated';

const useStyles = makeStyles((theme: Theme) => ({
  root: {
    marginTop: theme.spacing(8),
    marginBottom: theme.spacing(8),
    textAlign: 'center',
  },
}));

export const CtfDemo = (props: DemoFieldsFragment) => {
  const { title } = props;
  const classes = useStyles();
  return <div className={classes.root}>{title}</div>;
};
```

`src/components/features/ctf-components/ctf-demo/ctf-demo-gql.tsx`

React component which executes the GraphQL query and passes the result to a component for rendering.

```tsx
import { useContentfulLiveUpdates } from '@contentful/live-preview/react';
import React from 'react';

import { useCtfDemoQuery } from './__generated/ctf-demo.generated';
import { CtfDemo } from './ctf-demo';

interface CtfDemoGqlPropsInterface {
  id: string;
  locale: string;
  preview: boolean;
}

export const CtfDemoGql = ({ id, locale, preview }: CtfDemoGqlPropsInterface) => {
  const { data, isLoading } = useCtfDemoQuery({
    id,
    locale,
    preview,
  });

  const componentDemo = useContentfulLiveUpdates(data?.componentDemo, locale);

  if (isLoading || !componentDemo) {
    return null;
  }

  return <CtfDemo {...componentDemo} />;
};
```

## Add component to mapping

on `src/mappings.ts`

add import to demo component into `componetMap` and `componentGqlMap` constants

```tsx
export const componentMap = {
  ComponentDemo: dynamic(() => 
    import('@src/components/features/ctf-components/ctf-demo/ctf-demo').then(module => module.CtfDemo),
  ),
  ...
}

export const componentGqlMap = {
  ...pageTopicMap,
  ComponentDemo: dynamic(() =>
    import('@src/components/features/ctf-components/ctf-demo/ctf-demo-gql').then(
      module => module.CtfDemoGql,
    ),
  ),
  ...
}
```

## Run your code

```bash
yarn dev
```

You should see your component display on [http://localhost:3000/](http://localhost:3000/)

**Comment by cf-remylenoir** [comment]
Hi @zecka,

Thank you so much for the great feedback and for sharing your process to achieve your goal of creating a new Contentful component ❤️.

We actually dedicate some sections of the README to the [Contentful Components](https://github.com/contentful/template-marketing-webapp-nextjs/blob/main/README.md#contentful-components) and [how to create them](https://github.com/contentful/template-marketing-webapp-nextjs/blob/main/README.md#creating-new-contentful-components).

That said, we focus entirely on the code side of things and don't touch the Contentful Web App part.

We have a [tutorial](https://github.com/contentful/template-marketing-webapp-nextjs/blob/main/docs/tutorials/contentful-and-the-starter-template.md#relationship-between-contentful-and-the-starter-template) which guides one into what you basically had to do.

We mention this guide in the main [README](https://github.com/contentful/template-marketing-webapp-nextjs/blob/main/README.md#begin-your-journey-with-contentful-and-the-marketing-starter-template) but maybe it deserves more visibility/clarity?
